# Use postgres/example user/password credentials
version: '3.9'

services:

  mysql:
    image: mysql:8.3.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: test
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"

  postgres:
    image: postgis/postgis
    restart: always
    # set shared memory limit when using docker-compose
#    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: 1234
#      POSTGRES_DB: test
    ports:
      - '5432:5432'

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 1
    command: ["start-dev"]
    ports:
      - "3333:8080"